BookNest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("",include("library.urls") ),
    path("accounts/",include("accounts.urls")),
    path('admin/', admin.site.urls),
    
]

accounts/urls.py
from django.urls import path
from .import views

app_name = "accounts"

urlpatterns = [
    path("login/" , views.login_view , name = "login"),
    path("logout/" , views.logout_view , name = "logout")
]

library/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
import static

urlpatterns = [
    path("", views.index, name = "index"),
    path("books", views.books, name = "books"),
    path("forum", views.forum, name = "forum"),
    path("profile", views.profile, name = "profile"),
    path("addforum", views.addforum, name = "addforum"),
    path("about", views.about, name = "about"),
    path("contact", views.contact_view, name = "contact"),
    path('cart/', views.view_cart, name='view_cart'),
    path('borrow_books/', views.borrow_books, name='borrow_books'),
    path('view_borrowing_history/', views.view_borrowing_history, name='view_borrowing_history'),
    path('search/', views.search, name='search'),
    path('search_forum/', views.search_forum, name='search_forum'),
    path('add_to_cart/<int:book_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path("book_details/<int:id>", views.book_details, name = "book_details"),
    path("forum_details/<int:id>", views.forum_details, name = "forum_details"),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    
    

    
]

library/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# User Model
# class User(models.Model):
#     computerNumber = models.CharField(max_length=50 , unique=True)
#     username = models.CharField(max_length=50, unique=True)
#     password = models.CharField(max_length=255)  # Store hashed and salted passwords
#     email = models.EmailField(unique=True)
#     first_name = models.CharField(max_length=50, blank=True, null=True)
#     last_name = models.CharField(max_length=50, blank=True, null=True)
   

#     def __str__(self):
#         return self.username
    
# #Genre
# class Genre(models.Model):
#     genre = models.CharField(max_length=50, blank=True, null=True)
#     topic = models.CharField(max_length=50, blank=True, null=True)

#     def __str__(self):
#         name = self.genre
#         return name
    

# Book Model
class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=100)
    genre = models.CharField(max_length=50, blank=True, null=True)
    isbn = models.CharField(max_length=20, unique=True)
    description = models.TextField(blank=True, null=True)
    availability = models.BooleanField(default=True)
    book_picture = models.ImageField(upload_to='static/images', blank= True , null= True)



    def __str__(self):
        return self.title

# BorrowingHistory Model
class BorrowingHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    borrowed_date = models.DateField()
    due_date = models.DateField()
    return_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"{self.user}  borrowed  {self.book}  on  {self.borrowed_date}"

# UserRecommendation Model
class UserRecommendation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)



# ForumPost Model
class ForumPost(models.Model):
    forumid = models.AutoField(primary_key= True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    topic = models.CharField(max_length=50, blank=True, null=True)
    # comment = models.CharField(max_length=255 , blank= True , null= True )

    def __str__(self):
        return self.title
    

class Contact(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    message = models.CharField(max_length=500)

    def __str__(self):
        return f"Name : {self.name} ,  Phone : {self.phone},  Email : {self.phone},  Message : {self.message}"

class Comments(models.Model):
    comments = models.CharField(max_length=255)
    forumid= models.ForeignKey(ForumPost ,on_delete=models.CASCADE , blank = True , null = True )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    

    def __str__(self):
        return f"{self.comments} by {self.user.username}"
    

class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    added_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}'s Cart Item: {self.book.title}"

class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    computerNumber = models.CharField(max_length=50 , unique=True)
    

    def __str__(self):
        return f"{self.comments} by {self.user.username}"

library/forms.py
# forms.py
from django import forms
from . import models

class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comments
        fields = ['comments']
        
        #Compare this snippet from BookNest/library/templates/library/forum_details.html:
class AddPost(forms.ModelForm):
    class Meta:
        model = models.ForumPost
        fields = ['title','topic','content']

#Contact Form

class Contact(forms.ModelForm):
    class Meta:
        model = models.Contact
        fields = ['name','phone','email','message' ]
        
#Search Form
class SearchForm(forms.Form):
    query = forms.CharField(max_length=100, required=False)
        

library/views.py
from django.shortcuts import render , redirect , get_object_or_404
from .models import Book , ForumPost , User , Comments , Contact , CartItem ,BorrowingHistory , Profile
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from . import forms
from django.utils import timezone
from .forms import SearchForm





# Create your views here.
def index(request):
    return render(request , "library/index.html",{
        "books" : Book.objects.all(),
        "forums" : ForumPost.objects.all()
    })

def about(request):
    return render(request , "library/about.html")

def books(request):
    return render(request , "library/books.html" ,{
        "books" : Book.objects.all()
    })

def book_details(request , id):
    
    return render(request , "library/book_details.html" ,{
        "book" : Book.objects.get(pk=id),
    })

def forum(request):
    return render(request , "library/forum.html",{
        "forums" : ForumPost.objects.all()
    })

@login_required(login_url='/accounts/login/')
def addforum(request):
     if request.method == 'POST' :
        form = forms.AddPost(request.POST)
        if form.is_valid():
            #save comment to db
            #get the id for the post and post on that id 
            
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            
            return redirect('forum') 
     else:
        form = forms.AddPost()
     return render(request , "library/addforum.html",{
        "form" : form   
    })

def contact_view(request):
     if request.method == 'POST' :
        form = forms.Contact(request.POST)
        if form.is_valid():
            #save comment to db
            #get the id for the post and post on that id 
            
            instance = form.save(commit=False)
            instance.save()
            
            return redirect('index') 
     else:
        form = forms.Contact()
     return render(request , "library/contact.html",{
        "form" : form
       
    })


def forum_details(request , id):
    if request.method == 'POST' :
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            #save comment to db
            #get the id for the post and post on that id 
            
            instance = form.save(commit=False)
            instance.user = request.user
            instance.forumid = ForumPost.objects.get(pk=id)
            instance.save()
            
            return redirect('forum_details', id=id)
       
    else:
        form = forms.CommentForm()
    return render(request , "library/forum_details.html",{
        "forum":ForumPost.objects.get(pk=id),
        "forums" : ForumPost.objects.all(),
        "comment" : Comments.objects.filter(forumid=id),
        "form" : form
       
    })

def delete_comment(request, comment_id):
    comment = get_object_or_404(Comments, pk=comment_id)

    # Check if the user is the owner of the comment (optional)
    if request.user == comment.user:
        comment.delete()

    # Redirect back to the post details page or any other appropriate page
    return redirect('library/forum_details', id=comment.forumid.id)  # Redirect to the post details page

def delete_post(request, post_id):
    post = get_object_or_404(ForumPost, pk=post_id)

    # Check if the user is the owner of the post (optional)
    if request.user == post.user:
        post.delete()

    # Redirect back to the post details page or any other appropriate page
    return redirect('library/forum')  # Redirect to the post details page

@login_required(login_url='/accounts/login/')
def profile(request ):
    borrowing_history = BorrowingHistory.objects.filter(user=request.user).order_by('-borrowed_date')

    # Render the borrowing history in a template
    return render(request, 'library/profile.html',{
        'borrowing_history': borrowing_history,
        'profile': Profile.objects.all()
        })
  
        
   

###Cart Items
@login_required(login_url='/accounts/login/')
def view_cart(request):
    cart_items = CartItem.objects.filter(user=request.user)
    return render(request, 'library/cart.html', {'cart_items': cart_items})

@login_required(login_url='/accounts/login/')
def add_to_cart(request, book_id):
    book = Book.objects.get(id=book_id)
    cart_item = CartItem(user=request.user, book=book)
    cart_item.save()
    return redirect('view_cart')

@login_required(login_url='/accounts/login/')
def remove_from_cart(request, cart_item_id):
    cart_item = CartItem.objects.get(id=cart_item_id)
    cart_item.delete()
    return redirect('view_cart')

###### Borrowing books


@login_required(login_url='/accounts/login/')
def borrow_books(request):
    cart_items = CartItem.objects.filter(user=request.user)
    current_date = timezone.now().date()
    due_date = current_date + timezone.timedelta(days=14)  # You can adjust the due date as needed.

    for cart_item in cart_items:
        book = cart_item.book
        BorrowingHistory.objects.create(user=request.user, book=book, borrowed_date=current_date, due_date=due_date)
        book.availability = False
        book.save()

    # Clear the user's cart after borrowing.
    cart_items.delete()

    return redirect('view_borrowing_history')  # You can create a view for viewing borrowing history.

###### Borrowing History
@login_required(login_url='/accounts/login/')
def view_borrowing_history(request):
    # Retrieve the borrowing history for the current user
    borrowing_history = BorrowingHistory.objects.filter(user=request.user).order_by('-borrowed_date')

    # Render the borrowing history in a template
    return render(request, 'library/borrowing_history.html',{'borrowing_history': borrowing_history})


### Search View 


def search(request):
    if request.method == 'GET':
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Book.objects.filter(title__icontains=query)  # Example search by book title
        else:
            results = []
    else:
        form = SearchForm()
        results = []

    return render(request, 'library/search_results.html', {'form': form, 'results': results})


def search_forum(request):
    if request.method == 'GET':
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = ForumPost.objects.filter(title__icontains=query)  # Example search by book title
        else:
            results = []
    else:
        form = SearchForm()
        results = []

    return render(request, 'library/search_results_forum.html', {'form': form, 'results': results})

library/templates/library/about.html
{% extends "library/index.html" %}

{% load static %}

{% block body %}
    <div class="container">
        <h1>About Book Nest</h1>
        <p>Welcome to Book Nest, your gateway to a world of knowledge and imagination. We're passionate about making the joy of reading accessible to everyone, and our mission is to empower schools and libraries to create a seamless and enriching experience for their students and patrons.

            At Book Nest, we understand the evolving needs of educational institutions in the digital age. Our software solution offers a modern and efficient way for libraries to manage their book collections and for students to borrow books online, from anywhere, at any time.</p>
      
            
            <section id="mission">
                <h2>Our Mission</h2>
                <p>Welcome to Book Nest, your gateway to a world of knowledge and imagination. We're passionate about making the
                    joy of reading accessible to everyone, and our mission is to empower schools and libraries to create a
                    seamless and enriching experience for their students and patrons.</p>
            </section>
        
            <section id="commitment">
                <h2>Our Commitment</h2>
                <ul>
                    <li><strong>Bridging the Gap:</strong><p>We bridge the gap between traditional libraries and the digital era,
                        making it easier than ever for schools to embrace the future of learning.</p> </li>
                    <li><strong>Accessibility:</strong><p>We believe in the power of access. Book Nest enables students to explore a
                        vast library of resources and literary treasures with just a few clicks.</p> </li>
                    <li><strong>Empowering Educators:</strong><p>We empower educators to provide their students with a cutting-edge,
                        user-friendly tool for enhancing their reading and research experiences.</p> </li>
                    <li><strong>Seamless Integration:</strong><p>Our app seamlessly integrates with existing library systems,
                        ensuring a smooth transition into the digital age.</p> </li>
                    <li><strong>Security and Privacy:</strong><p> We prioritize the security and privacy of your data, ensuring that
                        sensitive information is protected at all times.</p></li>
                </ul>
            </section>
        
            <section id="why-choose">
                <h2>Why Choose Book Nest?</h2>
                <ul>
                    <li><strong>User-Friendly:</strong><p> Our intuitive interface makes borrowing books a breeze, even for
                        first-time users.</p></li>
                    <li><strong>Comprehensive Catalog:</strong><p>Explore an extensive catalog of books, journals, and reference
                        materials, carefully curated to cater to diverse tastes and educational needs.</p> </li>

                    <li><strong>Efficient Management:</strong><p>
                        Libraries can efficiently manage their book inventory, track
                        borrowing history, and generate insightful reports.
                    </p> </li>
                    <li><strong>Support and Community:</strong> <p>
                        We're here to support you every step of the way. Join the Book Nest
                        community, where learning and collaboration thrive.
                    </p> </li>
                </ul>
            </section>
        
            <section id="closing">
                <h2>Closing Thoughts</h2>
                <p>Book Nest is more than just an app; it's a commitment to fostering a love for reading, research, and lifelong
                    learning. Join us on this exciting journey as we redefine the way libraries and students interact with the
                    world of books.</p>
                <p>Thank you for choosing Book Nest as your partner in education and exploration.</p>
            </section>
    </div>
    <br><br><br>
 
{% endblock %}
   

library/templates/library/addforum.html
{% extends "library/index.html" %}

{% load static %}

{% block body %}

<div class="container">
    <section class="py-4 py-xl-5">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-5 col-xxl-4">
                    <div class="card mb-5">
                        <div class="card-body p-sm-5">
                            <h2 class="text-center mb-4">&nbsp;Forum Post</h2>
                            <form class="site-form"  method="post" action = "{% url 'addforum' %}">
                                
                                {% csrf_token %}
                                {{form}}
                                <input class = "btn btn-primary" type="submit" value="Add">
                                {% comment %} <select style="border-top-left-radius: 5px;border-top-right-radius: 5px;border-bottom-right-radius: 5px;border-bottom-left-radius: 5px;padding: 5px;border-style: none;" required="">
                                    <optgroup label="Topic">
                                        <option value="{{forum.topic}}" selected="">Engineering</option>
                                        <option value="{{forum.topic}}">Humanities</option>
                                        <option value="{{forum.topic}}">Business</option>
                                        <option value="{{forum.topic}}">Law</option>
                                        <option value="{{forum.topic}}">Medicine</option>
                                    </optgroup>
                                </select>
                                <div class="mb-3"></div>
                                <div class="mb-3"><input class="form-control" type="text" id="title" name="title" placeholder="Title" value="{{ forum.title }}"></div>
                                <div class="mb-3"><textarea class="form-control" type="text" id="content" name="content" rows="6" placeholder="Content" value="{{ forum.content }}" ></textarea></div> {% endcomment %}
                               
                            </form>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

library/templates/library/book_details.html
{% extends "library/layout.html" %}

{% load static %}

{% block body %}

<div class="container">
    <img src = {{ book.book_picture }} class="card-img-top w-100 d-block">
    <h1>{{ book.title }}</h1>
    <p class="card-text">Author : {{ book.author }}</p>
    <p class="card-text">Genre : {{ book.genre }}</p>
    <p class="card-text">{{ book.description }}</p>
    {% if user.is_authenticated %}
    <form method="post" action="{% url 'add_to_cart' book.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Borrow</button>
    </form>
    {% endif %}
</div>

        
<br><br><br><br><br>
<br>
<br>
<br><br><br><br>       
      
                    
                
{% endblock %}

library/templates/library/borrowing_history.html
{% extends "library/layout.html" %}
{% load static %}

{% block body %}
<div class="container">
    <h2>Your Borrowing History</h2>

     
         
             
   
        {% for entry in borrowing_history %}
         
             {{ entry.book.title }}
             <br>
             {{ entry.book.author }} 
             <br>
             {{ entry.borrowed_date }} 
             <br>
             {{ entry.due_date }} 
             <br>
             {{ entry.return_date }} 
         

        <hr>
        {% endfor %}
    
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

library/templates/library/cart.html
{% extends "library/layout.html" %}
{% load static %}

{% block body %}

<div class="container" >
    <h2>Your Cart</h2>

{% if cart_items %}

        {% for item in cart_items %}
        {{ item.book.title }}
        <br>
        {{ item.book.author }}
        <br>
                <a href="{% url 'remove_from_cart' item.id %}"><button class="btn btn-outline-danger btn-sm" type="submit">Remove</button></a>
            
                <hr>
        {% endfor %}
   
<a href="{% url 'borrow_books' %}"><button class="btn btn-primary btn-sm" type="submit">Borrow Now</button></a>
{% else %}
<p>Your cart is empty.</p>
{% endif %}

<a href="{% url 'index' %}"><button class="btn btn-outline-primary btn-sm" type="submit">Back to Home</button></a>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

{% endblock %}

library/templates/library/contact.html
{% extends "library/layout.html" %}
{% load static %}

{% block body %}
<form class = "site-form" action="{% url 'contact' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input class="btn btn-primary " type="submit" value="Send">
</form>
{% endblock %}

library/templates/library/forum_details.html
{% extends "library/layout.html" %}
{% load static %}

{% block body %}
<div class="container">
    <h1> {{forum.title}} </h1>
    <div>
        <p> {{ forum.content }} </p>
    </div>
    <hr style="width: 100%;">
    <h6>Comments</h6>
    
    <div>
        <p> {{ comment.forumid }} </p>
      
        {% for cm in comment %}
            <p> {{ cm.user }} </p>
            <p> {{ cm.comments }} </p>
            {% if comment.user == user %}
            <form class="site-form" method="post" action="{% url 'delete_comment' comment_id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
             {% endif %}

            <hr style="width: 60px;">
            {% empty %}
            <p> No Comments </p>
        {% endfor %}


    </div>

    {% comment %} <form action="{% url 'forum_details' forum.forumid %}" method="post">
        {% csrf_token %}
    <div class="d-flex"  style="width: 100%;padding: 5px; background-color: white; border-radius:20px; gap: 2px ">
        <div><input value="{{ comment.comment }}" class="border rounded border-0" type="text" placeholder="Add comment" name="comment"></div>
        <div><i class="material-icons" style="margin-left: 1rem;"> <input type="submit" value="send" > </i></div>
    </div>
    </form> {% endcomment %}
    {% if user.is_authenticated %}
    <form class = "site-form" action="{% url 'forum_details' id=forum.forumid %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Add Comment">
    </form>
    {% endif %}
</div>
<br>



{% comment %} <form action="{% url 'book' flight.id %}" method="post">
        {% csrf_token %}
       <select name="passenger" >
            {% for passenger in non_passengers %}
                <option value="{{ passenger.id }}">{{ passenger }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Book">
       </selector>

    </form> {% endcomment %}
{% endblock %}

library/templates/library/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Online Library Management System</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/Collapsible-Sidebar.css'%}">
    <link rel="stylesheet" href="{% static 'css/Off-Canvas-Sidebar-Drawer-Navbar.css'%}">
    <link rel="stylesheet" href="{% static 'css/Profile-Picture-With-Badge-profile-pic-with-badge.css'%}">
    <link rel="stylesheet" href="{% static 'css/Profile-Picture-With-Badge.css'%}">
    <link rel="stylesheet" href="{% static 'css/sidebar-style4.css'%}">
    <link rel="stylesheet" href="{% static 'css/sidebar.css'%}">
    <link rel="stylesheet" href="{% static 'css/forms.css'%}">
    <link rel="stylesheet" href="{% static 'css/Soft-UI-Aside-Navbar.css'%}">
</head>

<body>
    <nav class="navbar navbar-light navbar-expand-lg sticky-top" style="border-bottom-left-radius: 5px;border-bottom-right-radius: 5px;position: sticky; padding:0px;">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"> <img style="border-radius:50%;" width="70px" src="{% static 'img/logo.png'%} "> </a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link active" href="{% url 'about' %}">About Book Nest</a>
                        <hr class="d-print-none d-md-none d-lg-none d-xl-none d-xxl-none" style="width: 40px;">
                    </li>

                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'view_cart' %}">Cart</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'view_borrowing_history' %}">Borrowing History</a></li>
                    <hr class="d-print-none d-md-none d-lg-none d-xl-none d-xxl-none" style="width: 40px;">
                    <li class="nav-item"><a class="nav-link" href="{% url 'contact' %}">Contact</a></li>
                    <hr class="d-print-none d-md-none d-lg-none d-xl-none d-xxl-none" style="width: 40px;"> {% if user.is_authenticated %}
                    <li style="margin-bottom: 4px;" class="nav-item">
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-outline-primary btn-sm" type="submit">Logout</button>

                        </form>
                    </li>
                    {% else %}
                    <li style="margin-bottom: 4px;" class="nav-item">
                        <a href="{% url 'accounts:login' %}">

                            <button class="btn btn-outline-primary btn-sm" type="submit">Login</button>

                        </a>


                    </li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>

    <body>
        {% block body%} {% endblock %}
        <nav class="navbar navbar-light fixed-bottom border rounded border-0 d-lg-block" data-bs-toggle="tooltip" data-bss-tooltip="" data-bs-placement="bottom" style="margin-bottom: 0px;background: white;transform: perspective(0px) rotate(0deg) scale(1);transform-style: preserve-3d;position: sticky;display: block; padding:0.1rem;">
            <div class="container-fluid">
                <a class="nav-link" href="{% url 'index' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M21 8.77217L14.0208 1.79299C12.8492 0.621414 10.9497 0.621413 9.77817 1.79299L3 8.57116V23.0858H10V17.0858C10 15.9812 10.8954 15.0858 12 15.0858C13.1046 15.0858 14 15.9812 14 17.0858V23.0858H21V8.77217ZM11.1924 3.2072L5 9.39959V21.0858H8V17.0858C8 14.8767 9.79086 13.0858 12 13.0858C14.2091 13.0858 16 14.8767 16 17.0858V21.0858H19V9.6006L12.6066 3.2072C12.2161 2.81668 11.5829 2.81668 11.1924 3.2072Z" fill="currentColor"></path>
                </svg>
                </a>


                <a class="nav-link" href="{% url 'books' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-book">
                    <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"></path>
                </svg>
                </a>


                <a class="nav-link" href="{% url 'forum' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-chat-left">
                    <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4.414A2 2 0 0 0 3 11.586l-2 2V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"></path>
                </svg>
                </a>


                <a class="nav-link" href="{% url 'profile' %}">
                    <i class="fa fa-user-o" width="1em" height="1em"></i></div>
            </a>

        </nav>
        <script src="{% static 'bootstrap/js/bootstrap.min.js'%}"></script>
        <script src="{% static 'js/bs-init.js'%}"></script>
        <script src="{% static 'js/Off-Canvas-Sidebar-Drawer-Navbar-swipe.js'%}"></script>
        <script src="{% static 'js/Off-Canvas-Sidebar-Drawer-Navbar-off-canvas-sidebar.js'%}"></script>
        <script src="{% static 'js/Collapsible-Sidebar-Sidebar.js'%}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
        <script src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"></script>
    </body>

</html>